"""empty message

Revision ID: 065522cc61af
Revises: 
Create Date: 2021-03-27 19:44:20.612175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '065522cc61af'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wpi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('real', sa.Integer(), nullable=False),
    sa.Column('roman', sa.Integer(), nullable=False),
    sa.Column('human', sa.Integer(), nullable=False),
    sa.Column('ideal', sa.Integer(), nullable=False),
    sa.Column('agent', sa.Integer(), nullable=False),
    sa.Column('relation', sa.Integer(), nullable=False),
    sa.Column('trust', sa.Integer(), nullable=False),
    sa.Column('manual', sa.Integer(), nullable=False),
    sa.Column('self', sa.Integer(), nullable=False),
    sa.Column('culture', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sex', sa.Integer(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('wpi_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['wpi_id'], ['wpi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trainer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('sex', sa.Integer(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('wpi_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['wpi_id'], ['wpi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sale',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_sale', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('trainer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sale')
    op.drop_table('trainer')
    op.drop_table('member')
    op.drop_table('wpi')
    # ### end Alembic commands ###
