"""empty message

Revision ID: cdd7d35e09e9
Revises: 22b8a9762ea2
Create Date: 2021-03-26 14:18:27.959362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdd7d35e09e9'
down_revision = '22b8a9762ea2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wpi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('real', sa.Integer(), nullable=False),
    sa.Column('roman', sa.Integer(), nullable=False),
    sa.Column('human', sa.Integer(), nullable=False),
    sa.Column('ideal', sa.Integer(), nullable=False),
    sa.Column('agent', sa.Integer(), nullable=False),
    sa.Column('relation', sa.Integer(), nullable=False),
    sa.Column('trust', sa.Integer(), nullable=False),
    sa.Column('manual', sa.Integer(), nullable=False),
    sa.Column('self', sa.Integer(), nullable=False),
    sa.Column('culture', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gender', sa.Integer(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('wpi_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['wpi_id'], ['wpi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sale',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_sale', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('trainer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sale')
    op.drop_table('member')
    op.drop_table('wpi')
    # ### end Alembic commands ###
